### ISSUE TITLE
bl_info paragraph: Add the "version" and "Documentation+Report A Bug" buttons

### ISSUE THREAD

**Issue by xan2622** [maxivz/interactivetoolsblender#1]
Hi.

In the **bl_info** paragraph of your [__init__.py python file](https://github.com/maxivz/interactivetoolsblender/blob/master/__init__.py), could you please add these three lines? 

```
"version": (1, 0),
"wiki_url": "https://github.com/maxivz/interactivetoolsblender",
"tracker_url: "https://blenderartists.org/t/interactive-tools-for-blender-2-8/1164932",
```

These are just example URLs, feel free to use the links of your choice.

It will display the version of your addon (that is currently missing) and it will also add two new buttons in the Preferences > Addon details.

<img width="890" alt="Documentation_ReportABug" src="https://user-images.githubusercontent.com/1732773/59555523-f5f67b00-8fb3-11e9-8e7b-117ec28a72e3.png">

I think these buttons can be useful for users.
Thank you.

**Comment by maxivz** [comment]
Thanks for the suggestion! I fixed it in the last version :)
