### ISSUE TITLE
CS Move, CS Rotate, CS Scale do not get confirmed

### ISSUE THREAD

**Issue by BabyBonus** [maxivz/interactivetoolsblender#11]
Hi there,
I am having this issue in my file that the CS translations:
When I press the CS Translation hotkey a 2nd time to get the "Blender Mode" the actions do not get confirmed after i click. The tools stay active until i click again which ruins the translation as it "snaps" the object to where the cursor is.
This issue seems to be file specific. I have not pinned down yet why this is happening. Even when load factory settings and enable  InteractiveTools again the issue persists. In a fresh file it does not occure.
Did you ahve this issue at some point?
Thx

**Comment by BabyBonus** [comment]
I'm having the issue again. Appears only in my Animation workspace right now.

**Comment by BabyBonus** [comment]
So I was able to reproduce it! To me this issue happens after I split the viewport. Would be cool if you could confirm this. Thx

**Comment by DNollChimera** [comment]
This issue is still there. Can somebody test/confirm this plz

**Comment by BabyBonus** [comment]
If you split the view, you have to confirm for every 3d view that is there...

**Comment by maxivz** [comment]
This issue has been fixed in a new bug fix branch that will be merged into a new release soon. Thanks for reporting!
