### ISSUE TITLE
Blender 3.0: Applying Quick Lattice causes error to show

### ISSUE THREAD

**Issue by MightyDauntless** [maxivz/interactivetoolsblender#16]
Hi there, when I use 'Quick Lattice' to bridge my mesh between two objects and apply my Lattice shape Blender fires up an error. The error refers to 'float 2.90' I'm assuming this has something to do with the fact I am using Blender 3.0 and not Blender 2.90. Please check the video below, hope this can help resolve the thanks:

https://user-images.githubusercontent.com/99692564/153952807-76548cd9-7e6b-422a-b578-44f10e514b3f.mp4

Dauntless.

**Comment by maxivz** [comment]
Currently working in 3.5, please update the tools version and blender version.
