### ISSUE TITLE
preferences/hotkeys missing

### ISSUE THREAD

**Issue by vogues** [maxivz/interactivetoolsblender#17]
![image](https://user-images.githubusercontent.com/51140604/156871087-91d5c4dd-c1bd-46ea-87d7-2f72596f2e59.png)
i can not find this menu, nor are the hotkeys there, but the addon is installed and working from the panel.

im on 3.1

**Comment by vogues** [comment]
looks like 1.4 is on the git

**Comment by teachvisual** [comment]
had the same issue, it turned out I had the gumroad version witch is an old version, the github version has preferences
