### ISSUE TITLE
[BUG] Errors in Command Prompt

### ISSUE THREAD

**Issue by DropsMJay** [maxivz/interactivetoolsblender#20]
Im seeing this errors on the Command Prompt:
https://imgur.com/xGL9iIT

Im doing something wrong or the Addon is not updated to the last version of Blender?

Thank you.

**Comment by maxivz** [comment]
Hello! I think you have a really old version. I would advise that you update to the latest version that is on GitHub, that should solve it!

**Comment by DropsMJay** [comment]
Yep. I was using a wrong version. Thank you!
