### ISSUE TITLE
Not compatible with Blender 4.2

### ISSUE THREAD

**Issue by rwong111** [maxivz/interactivetoolsblender#24]
Just an artist who really likes your interactive tool. The issue seems to be due to the extensions implementation.
Thank you so much!!!!!!!!!!!!!!!

**Comment by Jordan-64** [comment]
I haven't tested it extensively but if you copy the file [https://raw.githubusercontent.com/blender/blender-addons/main/mesh_f2.py](https://github.com/maxivz/interactivetoolsblender/issues/url) into "Blender/4.2/scripts/addons" it seems to work.

**Comment by Jordan-64** [comment]
There is a Updated fork for Blender 4.2.0
https://github.com/ajfurey/interactivetoolsblender
You don't need the File i posted.

**Comment by iursingh** [comment]
Oh i didnt know a fork was updated for 4.2
Last i tried to use this one, I got so many error messages.

**Comment by iursingh** [comment]
> Just an artist who really likes your interactive tool. The issue seems to be due to the extensions implementation. Thank you so much!!!!!!!!!!!!!!!

Yea. I tried to use it on 4.0 as well. Get so many error and warning in the console. Too unstable. Going to try the fork as suggested above

**Comment by iursingh** [comment]
@Jordan-64 I tried the updated fork. I still get so many errors.

![Screenshot 2024-07-31 145106](https://github.com/user-attachments/assets/822245fb-ddea-45ed-94a6-686294ccd9eb)
![Screenshot 2024-07-31 145114](https://github.com/user-attachments/assets/85807a96-c822-4a30-9b96-e9c760c78d77)

**Comment by iursingh** [comment]
Reference #26 

Changing float 4 to 4.2 fixes this specific error in line 429.

**Comment by maxivz** [comment]
This should be fixed in the bugfix branch https://github.com/maxivz/interactivetoolsblender/tree/bugfixes
Its still in dev so there might be other bugs, but please give it a try and see if it works

**Comment by iursingh** [comment]
> This should be fixed in the bugfix branch https://github.com/maxivz/interactivetoolsblender/tree/bugfixes Its still in dev so there might be other bugs, but please give it a try and see if it works

Just tested this out, and yep, this has no errors whatsoever. 

Thank you so much. Nice work. Have tested most of things I use, they are all working without any issues.

**Comment by maxivz** [comment]
Ill close this issue as it has now been fixed in the new release, thanks everybody for reporting and contributing!

**Comment by rwong111** [comment]
THANK YOU!
