### ISSUE TITLE
Errors on 4.2

### ISSUE THREAD

**Issue by iursingh** [maxivz/interactivetoolsblender#26]
I get the same error again and again on 4.2 and even earlier 4.0 

Tried using the updated fork https://github.com/ajfurey/interactivetoolsblender and it has the same issues. 

![Screenshot 2024-07-31 145114](https://github.com/user-attachments/assets/c61b83ec-55fb-4c1f-b471-7e87a63a80f6)

**Comment by iursingh** [comment]
![Screenshot 2024-07-31 145106](https://github.com/user-attachments/assets/d5c7cfba-9973-4d45-a28a-05e09601f669)

**Comment by iursingh** [comment]
https://github.com/ajfurey 

@ajfurey @maxivz 

Can you help with it?

**Comment by ajfurey** [comment]
Hi it looks like 
float(bpy.app.version_string[:4]) >= 2.82: causes an error because version_string at position :4 = 4.2. which won't convert to float. float(bpy.app.version_string[:4.2]) >= 2.82: causes an error because version_string at position :4.2 doesn't exist. I think float(bpy.app.version_string[:3]) >= 2.82: is more correct because it will return the float 4.2. Thanks for pointing this mistake out I'll update my code tomorrow.

**Comment by iursingh** [comment]
Oh okay. Thank you.

**Comment by ajfurey** [comment]
I looked at your profile and the linked portfolio website and it was awesome! I like your props and environment art. You're way better than I am.

**Comment by iursingh** [comment]
> I looked at your profile and the linked portfolio website and it was awesome! I like your props and environment art. You're way better than I am.

Ohh. Thanks! 
You're too kind.

**Comment by iursingh** [comment]
Hey, btw I tried the updated fork again,

I have these errors, any idea how we can fix it? Syntax errors all of them. 

![image](https://github.com/user-attachments/assets/9b522ab8-61d7-4e4f-b09e-0e0199b520b6)

**Comment by maxivz** [comment]
I think this issue should be fixed in the bugfix branch. I am still working on other fixes so I will merge it later, but if you want to give it a try you can download and install this version: https://github.com/maxivz/interactivetoolsblender/tree/bugfixes
Let me know if it works :D

**Comment by iursingh** [comment]
> I think this issue should be fixed in the bugfix branch. I am still working on other fixes so I will merge it later, but if you want to give it a try you can download and install this version: https://github.com/maxivz/interactivetoolsblender/tree/bugfixes Let me know if it works :D

Oh okay. Thanks. :D Will test it out.

Also, what all is different in the @ajfurey branch with this one?

**Comment by maxivz** [comment]
I merged @ajfurey changes into the main branch but the error was still there. I replaced is not with != as thats the correct way to do it in Python now. I also fixed other issues other users were reporting

**Comment by iursingh** [comment]
@maxivz Amazing! Glad to get it working again in B4.2

It works really nice now.

**Comment by maxivz** [comment]
Ill close this issue as it has now been fixed in the new release, thanks everybody for reporting and contributing!
