### ISSUE TITLE
Context Sensitive Bevel doesn't work with Edges or Vertices

### ISSUE THREAD

**Issue by JustSaiyan01** [maxivz/interactivetoolsblender#7]
This is happing on Blender 2.91, didn't try 2.90 but I believe the python changes that might be causing this came into affect with 2.90.
https://wiki.blender.org/wiki/Reference/Release_Notes/2.90/Python_API
https://developer.blender.org/rB4aa2a5481cec

The specific issue is:

Traceback (most recent call last):
  File "C:\Users\jason\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\interactivetoolsblender-update8\op\misc.py", line 94, in execute
    self.cs_bevel()
  File "C:\Users\jason\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\interactivetoolsblender-update8\op\misc.py", line 88, in cs_bevel
    bpy.ops.mesh.bevel('INVOKE_DEFAULT', vertex_only=False)
  File "C:\blender-2.91.0-ba9c88ce1864-windows64\2.91\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Converting py args to operator properties: : keyword "vertex_only" unrecognized

location: <unknown location>:-1

**Comment by JustSaiyan01** [comment]
I've had a fix for the past few days and it seems to work with no issues, so thought I would post it for anyone needing it.
Got to the file misc.py, which is located in the op folder then go to line 84 & 87. 
Look for "vertex_only=True" and "vertex_only=false" and changed them to the following ---

affect='VERTICES' and affect='EDGES'

Like down below;

     if mode == 'VERT':
            bpy.ops.mesh.bevel('INVOKE_DEFAULT', affect='VERTICES')

        if mode == 'EDGE':
            bpy.ops.mesh.bevel('INVOKE_DEFAULT', affect='EDGES')

**Comment by maxivz** [comment]
Thanks a lot for letting me know! Ill try to push an update for 2.90 soon :)

**Comment by maxivz** [comment]
@JustSaiyan01 I have just pushed a quick fix for this, let me know if theres any problems :)

**Comment by JustSaiyan01** [comment]
@maxivz  Just done a quick test in both Blender 2.90 & 2.91, and no issues/errors have popped when bevelling in any of the different modes. So I guess it's fair to say that this is solved. Thank you :D
